language: node_js

node_js:
    - '4'
    - '6'
    - stable

install: 'npm install'

script: 'npm run gamut'

notifications:
    email: false

after_success:
    - bash <(curl -s https://codecov.io/bash)
